### ISSUE TITLE
event binding fails while initialize new Router(options)

### ISSUE THREAD

**Issue by llabball** [AmpersandJS/ampersand-router#23]
> When creating a new router, you may pass its routes hash directly as an option, if you choose. 

The route init want to read particular callbacks from the surrogate object. 
[`if (!callback) callback = this[name];`](https://github.com/AmpersandJS/ampersand-router/blob/master/ampersand-router.js#L43)

Problem is that the surrogate object is created in the `Router.extend()` function only. When passing the routes hash directly `this[name]` is always `undefined` and the event binding is broken.

Can the `extend` step be included in the constructor?

**Comment by lukekarrys** [comment]
An old issue, but I thought I'd chime in. The code to pass routes when initializing is

```js
var router = new Router({
  routes: {
    "help/:page":         "help",
    "download/*path":     "download",
    "folder/:name":       "openFolder",
    "folder/:name-:mode": "openFolder"
  }
})
```

I created #42 to clear up the documentation a bit and add a test for this for future regression purposes.

**Comment by llabball** [comment]
:+1:
