### ISSUE TITLE
Hash changes are impossible to follow

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-router#29]
If I have hashes that I want to track changes in, in addition to normal routing, this is impossible because getFragment() strips out the hash.  I know the url changed, but I don't know why without hacking in something tracking hash state on its own.

**Comment by ruiramos** [comment]
+1

**Comment by abradley2** [comment]
I have been having a similar issue but I'm not quite sure if it is related. It involves the hash in the url being mysteriously removed.

**Comment by krsyoung** [comment]
Hey @abradley2, did you ever have any luck with this?  I think I'm facing a similar issue - I keep losing the hash n the url.
