### ISSUE TITLE
Last index in execute args is always null

### ISSUE THREAD

**Issue by lokken** [AmpersandJS/ampersand-router#45]
I'm overriding the execute method to filter the query, just like in the documentation, but the last argument in args is always `null`. The documentation says that we can do `args.pop()` to get the query argument (assuming a route like `help/:query`), which makes sense, but since the last argument is always `null`, the pop just returns `null`.

I traced the issue to the `route.exec` call in `_extractParameters` so it seems that the regex used to extract the params always returns a `null` at the end. I can write a workaround for this in my overriding execute method but it seems incorrect for a `null` to be there.

On a side note, if you add an extra parameter to your route argument list, you get the `null` but any other extra parameters are `undefined`. So that `null` is passed on.

```
routes: {
    'help/:query': 'help'
},
help: function (query, nully, undef) {
    console.log(nully === null); // true
    console.log(undef === null); // false
    console.log(undef === undefined); // true
}
```

**Comment by beck** [comment]
Stumbled across same issue, opened pull: https://github.com/AmpersandJS/ampersand-router/pull/54
